apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - name: kafka-broker
        image: bitnami/kafka:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper.kafka:2181  # Correct service name for Zookeeper
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092  # Listen on all interfaces
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker.kafka.svc.cluster.local:9092  # FQDN for cross-namespace access
        ports:
        - containerPort: 9092