apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-cluster-role
rules:
  - apiGroups: [""]
    resources: 
      - "pods"
      - "pods/log"
      - "services"
      - "configmaps"
      - "secrets"
      - "persistentvolumeclaims"
    verbs: 
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
  - apiGroups: [""]
    resources:
      - "endpoints"
    verbs:
      - "get"
      - "list"
      - "watch"
