apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streaming-app
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-streaming-app
  template:
    metadata:
      labels:
        app: spark-streaming-app
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-streaming-app
        image: spark-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 4040
        env:
        - name: K8S_TOKEN
          valueFrom:
            secretKeyRef:
              name: spark-token-secret
              key: token
