apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-logs-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/spark/logs"  # Local directory in Minikube to store logs
