apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-driver
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-driver
  template:
    metadata:
      labels:
        app: spark-driver
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-driver
        image: spark-app:latest
        imagePullPolicy: Never
        command: ["/opt/bitnami/spark/bin/spark-submit"]
        args:
          [
            "--master", "k8s://https://kubernetes.default.svc",
            "--deploy-mode", "cluster",
            "--conf", "spark.kubernetes.container.image=spark-app:latest",
            "--conf", "spark.kubernetes.namespace=spark",
            "local:///opt/spark/app/spark_app.py"
          ]
        env:
        - name: SPARK_EXECUTOR_MEMORY
          value: "1G"
        - name: SPARK_EXECUTOR_CORES
          value: "1"
        - name: SPARK_DRIVER_MEMORY
          value: "1G"
        - name: SPARK_DRIVER_CORES
          value: "1"
        - name: SPARK_SUBMIT_OPTS
          value: "-Dspark.jars.ivy=/tmp/.ivy2"
        ports:
        - containerPort: 4040
          name: spark-ui
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 0.5
            memory: 1Gi
        volumeMounts:
        - name: spark-conf-volume-driver
          mountPath: /opt/spark/conf
        - name: ivy-cache
          mountPath: /tmp/.ivy2
      volumes:
      - name: spark-conf-volume-driver
        configMap:
          name: spark-drv-config
      - name: ivy-cache
        emptyDir: {}
