apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-executor
  namespace: spark
spec:
  serviceName: spark
  replicas: 2
  selector:
    matchLabels:
      app: spark-executor
  template:
    metadata:
      labels:
        app: spark-executor
    spec:
      containers:
      - name: spark-executor
        image: bitnami/spark:latest
        imagePullPolicy: Always
        env:
        - name: SPARK_WORKER_MEMORY
          value: "2G"
        - name: SPARK_WORKER_CORES
          value: "2"
        ports:
        - containerPort: 8081
          name: spark-worker-ui
