apiVersion: v1
kind: Service
metadata:
  name: spark-executor
  namespace: spark
spec:
  selector:
    app: spark-executor
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
